
--New tables, see documentation for further details--
CREATE TABLE SUSPICION(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_OF_SUSPICION VARCHAR(64) NOT NULL,
    TYPE_OF_SUSPICION VARCHAR(64) NOT NULL,
    SUBTYPE_OF_SUSPICION VARCHAR(64),
    DETAILS VARCHAR(500),
    MEDIA VARCHAR(200),
    ADDRESS VARCHAR(200) NOT NULL,
    LATITUDE DOUBLE PRECISION NOT NULL,
    LONGITUDE DOUBLE PRECISION NOT NULL,
    DATE1 VARCHAR(64) NOT NULL,
    TIME1 VARCHAR(64) NOT NULL
);


CREATE TABLE POLICE_LOGIN(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(64) NOT NULL,
    LAST_NAME VARCHAR(64) NOT NULL,
    USERNAME VARCHAR(64) NOT NULL,
    PASSWORD VARCHAR(64) NOT NULL
);

